name: Deploy Web App

on: push

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup python 
        uses: actions/setup-python@v4
        with:
          python-version: 3.6      

      - name: upgrade pip version
        run: python -m pip install --upgrade pip

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Unzip js.7z
        run: 7z x js.7z -o/static

      - name: Install MySQL
        uses: actions/setup-mysql@v2
        with:
          mysql-version: '8.0'
          db-name: 'ujn_a'
          db-user: 'root'
          db-password: 'zym233521'

      - name: Run server
        run: python server.py
